[MOB-10368] Reorganize some files

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -7,9 +7,9 @@ jobs:
     runs-on: macos-13
 
     steps:
-      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
+      - uses: actions/checkout@v4
 
-      - uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd # v1.6.0
+      - uses: maxim-lobanov/setup-xcode@v1
         with:
           xcode-version: latest-stable
 
@@ -18,15 +18,19 @@ jobs:
           xcrun simctl shutdown all || true
           xcrun simctl erase all || true
           xcrun simctl delete unavailable
-          RUNTIME=$(xcrun simctl list runtimes | grep "iOS" | grep -v unavailable | head -n 1 | awk '{print $1}')
+
+      - name: Create and Boot Simulator
+        run: |
+          RUNTIME=$(xcrun simctl list runtimes | grep "iOS-17-0" | awk '{print $NF}')
+          if [ -z "$RUNTIME" ]; then
+            echo "Error: Required iOS runtime not found!" >&2
+            exit 1
+          fi
           xcrun simctl create "iPhone-14-Pro-Max-CI" "iPhone 14 Pro Max" "$RUNTIME"
+          xcrun simctl boot "iPhone-14-Pro-Max-CI"
 
       - name: Verify Simulators
         run: xcrun simctl list devices
-
-      - name: Boot Simulator
-        run: |
-          xcrun simctl boot "iPhone-14-Pro-Max-CI"
 
       - name: Build and test with parallel testing
         run: |
